import 'dotenv/config.js'
import './events/index.js'
import './database/index.js'
import './api/app.js'
import './t-bot/index.js'
import './database/seeds/index.js'
import './bootstrap.js'
import './cron/index.js'